server:
  port: 9004

spring:
  application:
    name: auth-server
  datasource:
    username: newuser
    password: password
    url: jdbc:mysql://localhost:3406/authserverdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  #Eureka client discovery configuration
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka