#
#
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      student:
#        registerHealthIndicator: true
#        slidingWindowSize: 100
#        event-consumer-buffer-size: 10
#        slidingWindowType: COUNT_BASED
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
##    backendB:
##      registerHealthIndicator: true
##      slidingWindowSize: 10
##      permittedNumberOfCallsInHalfOpenState: 3
##      slidingWindowType: TIME_BASED
##      recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
#  timelimiter:
#    instances:
#      student:
#        timeoutDuration: 2s
#        cancelRunningFuture: true
##resilience4j:
##  timelimiter:
##    instances:
##      student:
##        timeoutDuration: 2s
##        cancelRunningFuture: true
##    backendB:
##      timeoutDuration: 1s
##      cancelRunningFuture: false